#!/usr/bin/bash
# Convert obj file with quads to obj file with triangles
cat quads.obj | sed -E -e "s/f ([0-9\/]+) ([0-9\/]+) ([0-9\/]+) ([0-9\/]+)/f \1 \2 \3`echo -e "\n"`f \1 \3 \4/g" > triangles.obj
